// src/components/PopupRelated/usePopupLogic.ts
import { useState, useEffect } from 'react';
import axios from 'axios';

interface LeadFormData {
  name: string;
  email: string;
  phone: string;
  address: string;
  marital_status: string;
  age: number | '';
  job: string;
  gender: string;
  consent_given: boolean;
  terms_accepted: boolean;
  marketing_consent: boolean;
}

interface DiscountInfo {
  amount: number;
  code: string;
  expiry: string;
}

export const usePopupLogic = () => {
  const [showPopup, setShowPopup] = useState(false);
  const [step, setStep] = useState<'wheel' | 'form' | 'success'>('wheel');
  const [discountInfo, setDiscountInfo] = useState<DiscountInfo | null>(null);
  const [phone, setPhone] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  // Calculate discount from phone
  const calculateDiscount = (phoneNumber: string): number => {
    const digits = phoneNumber.replace(/\D/g, '').split('');
    const sum = digits.reduce((acc, digit) => acc + parseInt(digit, 10), 0);
    return Math.min(sum, 100); // Cap at 100 EGP
  };

  // Validate Egyptian phone
  const validateEgyptianPhone = (phoneNumber: string): boolean => {
    const regex = /^01[0-2,5]{1}[0-9]{8}$/;
    return regex.test(phoneNumber);
  };

  // Handle spin completion
  const handleSpinComplete = () => {
    if (!validateEgyptianPhone(phone)) {
      setError('Please enter a valid Egyptian mobile number (01XXXXXXXXX)');
      return false;
    }

    const discountAmount = calculateDiscount(phone);
    setDiscountInfo({
      amount: discountAmount,
      code: '', // Will be generated by backend
      expiry: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString()
    });

    // Save to localStorage temporarily
    localStorage.setItem('fayrouz_temp_discount', discountAmount.toString());
    localStorage.setItem('fayrouz_temp_phone', phone);

    setStep('form');
    setError('');
    return true;
  };

  // Handle form submission
  const handleSubmitForm = async (formData: LeadFormData) => {
    setIsLoading(true);
    setError('');

    try {
      // Get UTM parameters from URL
      const urlParams = new URLSearchParams(window.location.search);
      const utm_source = urlParams.get('utm_source');
      const utm_medium = urlParams.get('utm_medium');
      const utm_campaign = urlParams.get('utm_campaign');

      const response = await axios.post('http://localhost:3001/api/website-leads', {
        ...formData,
        phone, // Use phone from wheel step
        page_visited: window.location.pathname,
        utm_source,
        utm_medium,
        utm_campaign,
        ip_address: '', // Backend will capture this
        user_agent: navigator.userAgent,
        referrer: document.referrer
      });

      // Save discount info from response
      setDiscountInfo(response.data.data.discount);

      // Mark as completed in localStorage
      localStorage.setItem('fayrouz_lead_completed', 'true');
      localStorage.setItem('fayrouz_discount_code', response.data.data.discount.code);
      localStorage.setItem('fayrouz_discount_amount', response.data.data.discount.amount.toString());
      localStorage.setItem('fayrouz_discount_expiry', response.data.data.discount.expiry);

      // Remove temp data
      localStorage.removeItem('fayrouz_temp_discount');
      localStorage.removeItem('fayrouz_temp_phone');

      setStep('success');
      
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  // Close popup
  const closePopup = () => {
    setShowPopup(false);
    // Don't show again for 24 hours
    localStorage.setItem('fayrouz_popup_last_closed', Date.now().toString());
  };

  // Initialize popup
  useEffect(() => {
    // Check if already completed
    const hasCompleted = localStorage.getItem('fayrouz_lead_completed');
    const lastClosed = localStorage.getItem('fayrouz_popup_last_closed');
    
    // Check if user is logged in (you'll need to implement this)
    const isLoggedIn = false; // Replace with your auth check

    if (hasCompleted || isLoggedIn) {
      return;
    }

    // Check if closed less than 24 hours ago
    if (lastClosed) {
      const twentyFourHours = 24 * 60 * 60 * 1000;
      if (Date.now() - parseInt(lastClosed) < twentyFourHours) {
        return;
      }
    }

    // Show after 6 seconds
    const timer = setTimeout(() => {
      setShowPopup(true);
    }, 6000);

    return () => clearTimeout(timer);
  }, []);

  // Restore temp data on mount
  useEffect(() => {
    const tempPhone = localStorage.getItem('fayrouz_temp_phone');
    const tempDiscount = localStorage.getItem('fayrouz_temp_discount');
    
    if (tempPhone && tempDiscount) {
      setPhone(tempPhone);
      setDiscountInfo({
        amount: parseInt(tempDiscount),
        code: '',
        expiry: ''
      });
      setStep('form');
    }
  }, []);

  return {
    showPopup,
    setShowPopup,
    step,
    setStep,
    discountInfo,
    phone,
    setPhone,
    isLoading,
    error,
    handleSpinComplete,
    handleSubmitForm,
    closePopup,
    validateEgyptianPhone
  };
};